export { default as EnrolSection } from "./enrol";
export { default as RegionSection } from "./region";
export { default as HowSection } from "./how";
export { default as WhatSection } from "./what";
export { default as WhenSection } from "./when";
export { default as WhereSection } from "./where";
export { default as WhoSection } from "./who";
export { default as WhySection } from "./why";
export { default as LandingSection } from "./landing";
